version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: userapi
    working_dir: /app
    container_name: userapi-app
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  db:
    image: mongo:latest
    container_name: userapi-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/data/db

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    driver: local